/**
 * @fileoverview Source File - Part of the application codebase
 * 
 * @author Abhishek Chandra <abhishek.chandra@csir.res.in>
 * @company Council of Scientific and Industrial Research, India
 * @license CSIR
 * @version 1.0.0
 * @since 2026-02-09
 */

import Papa from 'papaparse';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Downloads data as CSV
 */
export const exportToCSV = (data: any[], filename: string) => {
    if (!data || data.length === 0) {
        console.warn("No data to export");
        return;
    }

    const csv = Papa.unparse(data);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');

    if (link.download !== undefined) {
        const url = URL.createObjectURL(blob);
        link.setAttribute('href', url);
        link.setAttribute('download', `${filename}.csv`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
};

/**
 * Helper to convert an image URL or SVG to a Data URL (Base64)
 */
const getBase64Image = (url: string): Promise<string> => {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = 'Anonymous';
        img.onload = () => {
            const canvas = document.createElement('canvas');
            const scale = 2;
            canvas.width = img.width * scale;
            canvas.height = img.height * scale;
            const ctx = canvas.getContext('2d');
            if (ctx) {
                ctx.scale(scale, scale);
                ctx.drawImage(img, 0, 0);
                resolve(canvas.toDataURL('image/png'));
            } else {
                reject(new Error('Canvas context not available'));
            }
        };
        img.onerror = () => reject(new Error(`Failed to load image: ${url}`));
        img.src = url;
    });
};

/**
 * Draws a professional semi-transparent watermark on the page.
 */
const drawWatermark = (pDoc: jsPDF) => {
    const pageWidth = pDoc.internal.pageSize.getWidth();
    const pageHeight = pDoc.internal.pageSize.getHeight();

    pDoc.saveGraphicsState();

    // Transparency management
    try {
        const GState = (jsPDF as any).GState || (pDoc as any).GState;
        if (GState) {
            pDoc.setGState(new GState({ opacity: 0.12 }));
        } else if (typeof (pDoc as any).setAlpha === 'function') {
            (pDoc as any).setAlpha(0.15);
        }
    } catch (e) {
        pDoc.setTextColor(240, 240, 240);
    }

    pDoc.setTextColor(150, 150, 150);
    pDoc.setFontSize(50); // Reduced for better centering and fit
    pDoc.setFont("helvetica", "bold");

    // Centered diagonal
    pDoc.text("INTERNAL USE ONLY", pageWidth / 1.6, pageHeight / 1.2, {
        align: 'center',
        angle: 45
    });

    pDoc.restoreGraphicsState();
};

/**
 * Downloads data as PDF table (General List Report)
 */
export const exportToPDF = async (
    data: any[],
    columns: { header: string; dataKey: string }[],
    title: string,
    filename: string,
    exportedBy?: string,
    filterSummary?: string,
    orientation: 'portrait' | 'landscape' = 'landscape',
    logoUrl?: string
) => {
    if (!data || data.length === 0) return;

    const doc = new jsPDF({ orientation });
    const pageWidth = doc.internal.pageSize.getWidth();

    let base64Logo = "";
    if (logoUrl) {
        try {
            base64Logo = await getBase64Image(logoUrl);
        } catch (e) { }
    }

    if (base64Logo) {
        doc.addImage(base64Logo, 'PNG', pageWidth - 49, 8, 35, 35, undefined, 'FAST');
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(title, 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(79, 70, 229);
    doc.text("Generated on: ", 14, 28);
    const genWidth = doc.getTextWidth("Generated on: ");
    doc.setTextColor(0, 0, 0);
    doc.text(new Date().toLocaleString(), 14 + genWidth, 28);

    let currentY = 34;
    if (exportedBy) {
        doc.setTextColor(79, 70, 229);
        doc.text("Generated by: ", 14, currentY);
        const expWidth = doc.getTextWidth("Generated by: ");
        doc.setTextColor(0, 0, 0);
        doc.text(exportedBy, 14 + expWidth, currentY);
        currentY += 6;
    }

    doc.setTextColor(79, 70, 229);
    doc.text("Filters: ", 14, currentY);
    const filterWidth = doc.getTextWidth("Filters: ");
    doc.setTextColor(0, 0, 0);
    const summaryText = filterSummary || "-NIL-";
    const splitText = doc.splitTextToSize(summaryText, pageWidth - filterWidth - 28);
    doc.text(splitText, 14 + filterWidth, currentY);
    currentY += (splitText.length * 5) + 6;

    if (currentY < 48 && base64Logo) currentY = 48;

    const tableHeaders = columns.map(c => c.header);
    const tableData = data.map(row => columns.map(col => row[col.header] || ''));

    autoTable(doc, {
        head: [tableHeaders],
        body: tableData,
        startY: currentY,
        theme: 'plain',
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255] },
        margin: { left: 14, right: 14 }
    });

    const totalPages = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        drawWatermark(doc);
    }

    doc.save(`${filename}.pdf`);
};

/**
 * Generates a detailed PDF report for a single reference and its movements
 */
export const exportReferenceReportPDF = async (
    reference: any,
    movements: any[],
    title: string,
    filename: string,
    exportedBy?: string,
    logoUrl?: string,
    orientation: 'portrait' | 'landscape' = 'landscape',
    reportType?: string
) => {
    const doc = new jsPDF({ orientation });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const getUserDisplay = (user: any) => {
        if (!user) return "N/A";
        if (typeof user === 'string') return user;
        const name = user.fullName || "Unknown";
        const designation = user.designation ? `, ${user.designation}` : "";
        const lab = user.labName ? ` (${user.labName})` : "";
        return `${name}${designation}${lab}`;
    };

    let base64Logo = "";
    if (logoUrl) {
        try {
            base64Logo = await getBase64Image(logoUrl);
        } catch (e) { }
    }

    const decoratePage = (pDoc: jsPDF, pageNum: number, total: number) => {
        pDoc.saveGraphicsState();
        pDoc.setFillColor(255, 255, 255);
        pDoc.rect(0, 0, pageWidth, 60, 'F');

        pDoc.setDrawColor(79, 70, 229);
        pDoc.setLineWidth(1.5);
        pDoc.line(0, 0, pageWidth, 0);

        if (base64Logo) {
            pDoc.addImage(base64Logo, 'PNG', 10, 8, 35, 35, undefined, 'FAST');
        }

        const isLocal = title.toLowerCase().includes('local');
        const lab = reference.labName || (reference.createdByDetails?.labName) || "";

        pDoc.setTextColor(79, 70, 229);
        pDoc.setFont("helvetica", "bold");
        pDoc.setFontSize(orientation === 'landscape' ? 9 : 8);
        pDoc.text("COUNCIL OF SCIENTIFIC & INDUSTRIAL RESEARCH", pageWidth - 14, 15, { align: 'right' });

        if (isLocal && lab) {
            pDoc.setFontSize(orientation === 'landscape' ? 15 : 13);
            pDoc.text(lab.toUpperCase(), pageWidth - 14, 26, { align: 'right' });
            pDoc.setTextColor(31, 41, 55);
            pDoc.setFontSize(orientation === 'landscape' ? 20 : 18);
            pDoc.text("Reference Movement Details", pageWidth - 14, 38, { align: 'right' });
        } else {
            pDoc.setTextColor(31, 41, 55);
            pDoc.setFontSize(orientation === 'landscape' ? 22 : 20);
            pDoc.text("Reference Movement Details", pageWidth - 14, 32, { align: 'right' });
        }

        pDoc.setFontSize(8);
        pDoc.setFont("helvetica", "normal");
        pDoc.setTextColor(107, 114, 128);
        pDoc.text("CSIR Reference Management System", pageWidth - 14, isLocal && lab ? 45 : 42, { align: 'right' });

        pDoc.setDrawColor(229, 231, 235);
        pDoc.setLineWidth(0.5);
        pDoc.line(14, 54, pageWidth - 14, 54);

        const footerY = pageHeight - 15;
        pDoc.setDrawColor(79, 70, 229);
        pDoc.line(14, footerY - 5, pageWidth - 14, footerY - 5);
        pDoc.setFontSize(8);
        pDoc.setTextColor(156, 163, 175);
        pDoc.text(`Generated by: ${exportedBy || 'System'} on ${new Date().toLocaleString()}`, 14, footerY);
        pDoc.text(`© ${new Date().getFullYear()} CSIR`, pageWidth - 14, footerY, { align: 'right' });

        // Place page number on a separate line to avoid overlap in portrait mode
        pDoc.setFont("helvetica", "bold");
        pDoc.setFontSize(9);
        pDoc.text(`Page ${pageNum} of ${total}`, pageWidth / 2, footerY + 5, { align: 'center' });
        pDoc.restoreGraphicsState();

        drawWatermark(pDoc);
    };

    // Rendering Content
    let currentY = 70; // Slightly more padding
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Reference Details :", 14, currentY);
    currentY += 8;

    const detailsData = [
        ["Subject:", reference.subject || "N/A"],
        ["Ref ID:", reference.refId || "N/A"],
        ["Ref Type:", reportType || "N/A"],
        ["Status:", reference.status || "N/A"],
        ["Priority:", reference.priority || "N/A"],
        ["Delivery Mode:", reference.deliveryMode || "N/A"],
        ["E-office No:", reference.eofficeNo || "N/A"],
        ["Created By:", getUserDisplay(reference.createdBy)],
        ["Created On:", new Date(reference.createdAt).toLocaleDateString()],
        ["Latest Remarks:", reference.remarks || "No remarks provided."]
    ];

    autoTable(doc, {
        body: detailsData,
        startY: currentY,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2, textColor: [0, 0, 0] },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 40, textColor: [79, 70, 229] },
            1: { cellWidth: 'auto' }
        },
        margin: { left: 14, right: 14, top: 70 }
    });

    currentY = (doc as any).lastAutoTable.finalY + 15;
    if (currentY > pageHeight - 60) {
        doc.addPage();
        currentY = 75;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`Movement History for- ${reference.refId || 'N/A'} :`, 14, currentY);
    currentY += 8;

    const moveRows = movements.map(m => [
        new Date(m.movementDate).toLocaleDateString(),
        getUserDisplay(m.performedBy),
        m.statusOnMovement,
        m.remarks || "-",
        Array.isArray(m.markedTo) ? m.markedTo.map((u: any) => getUserDisplay(u)).join("; ") : getUserDisplay(m.markedTo)
    ]);

    autoTable(doc, {
        head: [["Date", "Action By", "Status", "Remarks", "Marked To"]],
        body: moveRows,
        startY: currentY,
        theme: 'plain',
        styles: { fontSize: orientation === 'landscape' ? 9 : 8, cellPadding: 3, valign: 'middle', textColor: [0, 0, 0] },
        headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255] },
        columnStyles: orientation === 'landscape'
            ? { 0: { cellWidth: 25 }, 1: { cellWidth: 55 }, 2: { cellWidth: 35 }, 3: { cellWidth: 'auto' }, 4: { cellWidth: 55 } }
            : { 0: { cellWidth: 22 }, 1: { cellWidth: 45 }, 2: { cellWidth: 30 }, 3: { cellWidth: 'auto' }, 4: { cellWidth: 45 } },
        margin: { left: 14, right: 14, top: 70, bottom: 25 }
    });

    const totalPagesCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= totalPagesCount; i++) {
        doc.setPage(i);
        decoratePage(doc, i, totalPagesCount);
    }

    doc.save(`${filename}.pdf`);
};
